apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: secret-env-pod
      image: docker-registry.default.svc:5000/acs/nginx-example
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              key: username
              name: db-secrets
        - name: password
          valueFrom:
            secretKeyRef:
              key: password
              name: db-secrets
        - name: hostname
          valueFrom:
            secretKeyRef:
              key: hostname
              name: db-secrets
        - name: dbname
          valueFrom:
            secretKeyRef:
              key: dbname
              name: db-secrets
