apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep
  name: mydep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydep
  strategy: {}
  template:
    metadata:

      labels:
        app: mydep
    spec:
      containers:
      - image: nginx
        name: nginx

