apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-acs-limit
  namespace: acs
spec:
  hard:
    pods: '4'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '1'
    limits.memory: '1Gi'
