apiVersion: v1
kind: Pod
metadata:
  name: bigpod
spec:
  containers:
  - image: openshift/hello-openshift
    name: hello-openshift
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 200m
        memory: 2Gi