apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-developer-limit
  namespace: acs
spec:
  hard:
    pods: '2'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '1'
    limits.memory: '1Gi'
