apiVersion: v1
kind: Pod
metadata:
  name: one-container
  namespace: acs
  label:
    app: apf
spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

