apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: acs
spec:
  ports:
  - name: mysql
    nodePort: 30306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: NodePort
