kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  namespace: acs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-vol-pod
  template:
    metadata:

      labels:
        app: secret-vol-pod
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: db-secrets
      containers:
        - name: secret-vol-pod
          image: image-registry.openshift-image-registry.svc:5000/acs/nginx-example
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /etc/secret-volume





