kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "hello"
spec:
  template:
    metadata:
      labels:
        name: "hello"
    spec:
      containers:
        - name: "helloworld"
          image: "openshift/hello-openshift"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 5
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "helloworld"
        from:
          kind: "ImageStreamTag"
          name: "hello-openshift:latest"
  strategy:
    type: "Rolling"
